





POST http://localhost:6969/stories
Content-Type: application/json

{
    "Storie_Sub_Title": "Stories_Sub_Title",
    "Storie_Tags": ["tag1","tag2","tag3","tag4","tag5","tag6","tag7"
                    ,"tag8","tag9","tag10","tag11","tag12"],
    "created_by": "6140a9a7606c8058f7ecbf93"
}   








    